<style>
h6{
	font-weight: bold;
}
</style>

<div class="row">
	<div class="col s12">
		<h5 class="center-align"> Bienvenido Dr. <?=$this->user->getNombreCompleto()?> </h5>
		<h5 class="center-align"> Su lista de citas pendientes: </h5> 
	</div>
</div>
<div class="row">
	<div class="col s6">
		<h6 class="left-align"> Para obterner m&aacute;s informaci&oacute;n de cada cita, de click en la cita deseada. </h6>
	</div>
</div>
<div id="lista_pacientes" class="row">
	<div class="col s12">
	<table class="responsive-table hoverable">
        <thead>
          <tr>
              <th data-field="fecha_cita">Fecha de Cita</th>
              <th data-field="hora_cita">Hora de Cita</th>
              <th data-field="lugar_cita">Lugar de Cita </th>
              <th data-field="nombre_paciente"><h6 class="center-align">Nombre del Paciente</h6></th>
          </tr>
        </thead>

        <tbody>
        <?php $n = 0;
         foreach ($this->solicitud->getSolicitudes() as $key) :
        $n++; ?>
          <tr> 
            <td><a class="waves-effect waves-light modal-trigger" href="#modal<?=$n?>"><?php echo explode(" ", $key['fecha'])[0];?></a></td>
            <td><a class="waves-effect waves-light modal-trigger" href="#modal<?=$n?>"><?php echo explode(" ", $key['fecha'])[1];?></a></td>
            <td><a class="waves-effect waves-light modal-trigger" href="#modal<?=$n?>">Aqu&iacute; va EL LUGAR (SICSA, ELISEO, ETC.) falta relacion</a></td>
            <td><a class="waves-effect waves-light modal-trigger" href="#modal<?=$n?>"><?=$key['pnombre']?> <?=$key['pap']?> <?=$key['pam']?></a></td>
          </tr>
          <div id="modal<?=$n?>" class="modal">
              <div class="modal-content">
                <h4>Detalle de cita del paciente: <?=$key['pnombre']?> <?=$key['pap']?> <?=$key['pam']?></h4>
                <div class="row">
                  <div class="col s6">
                    <h6 class="center-align"> Empresa: </h6>
                  </div>
                  <div class="col s6"> 
                    <h6 class="center-align"><?=$key['cnombre']?> </h6>
                  </div>
                </div>
                <div class="row">
                  <div class="col s6">
                    <h6 class="center-align"> Estudios a realizar: </h6>
                  </div>
                  <div class="col s6"> 
                    <h6 class="center-align"> Pendiente </h6>
                  </div>
                </div>
                <div class="row">
                  <div class="col s6">
                    <h6 class="center-align"> Autorizado por: </h6>
                  </div>
                  <div class="col s6"> 
                    <h6 class="center-align"> <?=$key['rnombre']?> <?=$key['rap']?> <?=$key['ram']?> </h6>
                  </div>
                </div>
                <div class="row">
                  <div class="col s6">
                    <h6 class="center-align"> Observaciones: </h6>
                  </div>
                  <div class="col s6"> 
                    <h6 class="center-align"><?=$key['observaciones']?> </h6>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OK</a>
              </div>
            </div>
        <?php endforeach; ?>
        </tbody>
      </table>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('.modal-trigger').leanModal();
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  });
</script>