<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<!--Import materialize.css-->
	<link type="text/css" rel="stylesheet" href="/css/materialize.min.css"  media="screen,projection"/>
	<link type="text/css" rel="stylesheet" href="/css/default.css"	media="screen,projection" />
	<link type="text/css" rel="stylesheet" href="/css/default.date.css"	media="screen,projection" />
	<link type="text/css" rel="stylesheet" href="/css/default.time.css"	media="screen,projection" />
	<link type="text/css" rel="stylesheet" href="/css/style.css"	media="screen,projection" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<title>PISYE Alpha</title>
	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

	<!--Import jQuery before materialize.js-->
	<!--<script type="text/javascript" src="/js/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script> -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="/js/simpler-sidebar-1.3.4/dist/jquery.simpler-sidebar.min.js"></script>
	<script type="text/javascript" src="/js/picker.js"></script>
	<script type="text/javascript" src="/js/picker.date.js"></script>
	<script type="text/javascript" src="/js/picker.time.js"></script>
	<script type="text/javascript" src="/js/materialize.min.js"></script>
</head>

<body>
<div class="sitecontent">
<div class="navbar-fixed">
	<nav class="yellow accent-4 black-text">
		<div class="nav-wrapper ">
			<div id="main-navbar" class="main-navbar main-navbar-fixed-top">
	              <div class="main-navbar-content">
	                  	<div id="toggle-sidebar" class="left">
	                  		<i class="fa fa-bars"></i>
	                  	</div>
	              </div>
	        </div>
			<a href="/" class="brand-logo center">PISYE<span class="black-text text-darken-4">Alpha</span></a>

			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<?php if($this->auth->isAuth()) : ?>
					<li><a href="/User/logout">Logout: <?=$this->user->getUsername();?></a></li>
				<?php else : ?>
					<li><a href="/User">Login</a></li>
				<?php endif; ?>
			</ul>
			<ul class="side-nav" id="mobile-demo">
		        <?php if($this->auth->isAuth()) : ?>
					<li><a href="/User/logout">Logout: <?=$this->user->getUsername();?></a></li>
				<?php else : ?>
					<li><a href="/User">Login</a></li>
				<?php endif; ?>
		     </ul>
		</div>
	</nav>
</div>
<div id="main-sidebar" class="main-sidebar main-sidebar-left">
	<div id="main-sidebar-wrapper" class="main-sidebar-wrapper">
	<?php if($this->auth->isAuth()) :
		$obj= $this->user->getUserObject();
		if ($this->user->getUserType() == 'Maestro'): ?>
		<div class="section">
			<img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
			<p class="nombre-sidebar"> Maestro <?=$this->user->getNombreCompleto()?> </p>
			<nav>
				<ul>
					<li class="lista-sidebar"><a href="/Maestro/index" class="active">Inicio</a></li>
					<li class="lista-sidebar"><a href="#" >accion 2</a></li>
					<li class="lista-sidebar"><a href="/User/logout" class="boton-logout">Cerrar Sesion</a></li>
				</ul>
			</nav>
		</div>
	<?php elseif ($this->user->getUserType() == 'Administrador'): ?>
		<div class="section">
			<img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
			<p class="nombre-sidebar"> Administrador <br><br> <?=$this->user->getNombreCompleto()?> </p>
			<nav>
				<ul>
					<li class="lista-sidebar"><a href="/Admin/" class="lista-sidebar">Inicio</a></li>
					<li class="lista-sidebar"><a href="/Admin/users" class="lista-sidebar">Gesti&oacute;n de usuarios</a></li>
					<li class="lista-sidebar"><a href="#" class="lista-sidebar">#####</a></li>
					<li class="lista-sidebar"><a href="/User/logout" class="boton-logout">Cerrar Sesion</a></li>
				</ul>
			</nav>
		</div>
	<?php elseif ($this->user->getUserType() == 'Alumno'): ?>
		<div class="section">
			<img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
			<p class="nombre-sidebar"> Empresa <b><b> <?=$this->user->getNombreCompleto()?> </p>
			<nav>
				<ul>
					<li class="lista-sidebar"><a href="/Alumno/index" class="lista-sidebar">Inicio</a></li>
					<li class="lista-sidebar"><a href="#" class="lista-sidebar">#####</a></li>
					<li class="lista-sidebar"><a href="/User/logout" class="boton-logout">Cerrar Sesion</a></li>
				</ul>
			</nav>
		</div>
	<?php endif; //de user object ?>
	<?php else : ?>
		<div class="section">
			<nav>
				<ul>
					<li class="lista-sidebar"><a href="/User">Login</a></li>
				</ul>
			</nav>
		</div>
		<?php endif; //de autenticacion?>
	</div>
</div>
 	<?php echo $this->view; ?>
 	</div>
	<footer class="page-footer yellow accent-4 black-text">
		<div class="footer-copyright black-text">
			<div class="container">
				© 2015 Copyright Hagane Software
			</div>
		</div>
	</footer>
<script>
            $(document).ready(function() {
                $('#main-sidebar').simplerSidebar({
                    opener: '#toggle-sidebar',
                    animation: {
                        easing: "easeOutExpo"
                    },
                    sidebar: {
                        align: 'left',
                        width: 360,
                        backgroundColor: 'black',
                        closingLinks: '.close-sb'

                    }

                });

            });
</script>
<script type="text/javascript">
$(document).ready(function(){
	$('.scrollspy').scrollSpy();
	$('.button-collapse').sideNav({
      menuWidth: 300, // Default is 240
      closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    }
  );
});
</script>
</body>
</html>
