<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8"> 
	<!--Import materialize.css-->
	<link type="text/css" rel="stylesheet" href="/css/materialize.min.css"  media="screen,projection"/>
	<link type="text/css" rel="stylesheet" href="/css/default.css"	media="screen,projection" />
	<link type="text/css" rel="stylesheet" href="/css/default.date.css"	media="screen,projection" />
	<link type="text/css" rel="stylesheet" href="/css/default.time.css"	media="screen,projection" />

	<title>SISSE Alpha</title>
	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

		<!--Import jQuery before materialize.js-->
	<!--<script type="text/javascript" src="/js/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script> -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="/js/picker.js"></script>
	<script type="text/javascript" src="/js/picker.date.js"></script>
	<script type="text/javascript" src="/js/picker.time.js"></script>
	<script type="text/javascript" src="/js/materialize.min.js"></script>
    <script type="text/javascript"> 
	$(document).ready(function () {
	    var navListItems = $('div.setup-panel div a'),
	            allWells = $('.setup-content'),
	            allNextBtn = $('.nextBtn');
	    allWells.hide();
	    navListItems.click(function (e) {
	        e.preventDefault();
	        var $target = $($(this).attr('href')),
	                $item = $(this);
	        if (!$item.hasClass('disabled')) {
	            navListItems.removeClass('btn-info').addClass('btn-default');
	            $item.addClass('btn-info');
	            allWells.hide();
	            $target.show();
	            $target.find('input:eq(0)').focus();
	        }
	    });
	    allNextBtn.click(function(){
	        var curStep = $(this).closest(".setup-content"),
	            curStepBtn = curStep.attr("id"),
	            nextStepWizard = $('div.setup-panel div a[href="#' + curStepBtn + '"]').parent().next().children("a"),
	            curInputs = curStep.find("input[type='text'],input[type='url']"),
	            isValid = true;
	        $(".form-group").removeClass("has-error");
	        if (isValid)
	            nextStepWizard.removeAttr('disabled').trigger('click');
	    });
	    $('div.setup-panel div a.btn-info').trigger('click');
        $('#checkboxdisposicion').change(function () {
            if ($(this).prop('checked') === true) {
                $('#cualesgroup').show();
                $('input[name=cuales').prop('required',true);
            } else {
                $('#cualesgroup').hide();
                $('input[name=cuales').prop('required',false);
            }
        });
        $('#checkboxinmunizaciones').change(function () {
            if ($(this).prop('checked') === true) {
                $('#inmunizacionesgroup').show();
            } else {
                $('#inmunizacionesgroup').hide();
            }
        });
        $('#checkboxdrogadiccion').change(function () {
            if ($(this).prop('checked') === true) {
                $('#drogadiccionesgroup').show();
            } else {
                $('#drogadiccionesgroup').hide();
            }
        });
        $('#checkboxcondicion').change(function () {
            if ($(this).prop('checked') === true) {
                $('#cualcondiciongroup').show();
            } else {
                $('#cualcondiciongroup').hide();
            }
        });

        $('input').on("change", function(){
        	var $variable = $(this).data('name');
	        if($variable){
		        if( ($variable+'no') == $(this)[0].id ) {
		            if ($(this).prop('checked') === true) {
		            	$('#'+$variable+'dxfield').hide();
		            	$('#'+$variable+'txfield').hide();
		            	$('#'+$variable+'dx').parent().removeClass('active');
		            	$('#'+$variable+'tx').parent().removeClass('active');
		            } else {
		            }
		        }
		        if ( ($variable+'dx') == $(this)[0].id ) {
		            if ($(this).prop('checked') === true) {
		                $('#'+$variable+'dxfield').show();
		                $('#'+$variable+'no').parent().removeClass('active');
		            } else {
		                $('#'+$variable+'dxfield').hide();
		            }
		        }
		        if ( ($variable+'tx') == $(this)[0].id ) {
		            if ($(this).prop('checked') === true) {
		                $('#'+$variable+'txfield').show();
		                $('#'+$variable+'no').parent().removeClass('active');
		            } else {
		                $('#'+$variable+'txfield').hide();
		            }
		        }

		        if( ($variable+'dx') == $(this)[0].id || ($variable+'tx') == $(this)[0].id ){
		        	if( $('#'+$variable+'dx').prop('checked') === false && $('#'+$variable+'tx').prop('checked') === false )
		        		$('#'+$variable+'no').parent().addClass('active');
		        }
		    }
        });

        $('#anticonceptivos').change(function () {
            if ($(this).prop('checked') === true) {
                $('#anticonceptivoscualesgroup').show();
                $('input[name=anticonceptivoscuales').prop('required',true);
            } else {
                $('#anticonceptivoscualesgroup').hide();
                $('input[name=anticonceptivoscuales').prop('required',false);
            }
        });
        $('#abortos').change(function () {
            if ($(this).prop('checked') === true) {
                $('#abortoscuantosgroup').show();
                $('input[name=abortoscuantos').prop('required',true);
            } else {
                $('#abortoscuantosgroup').hide();
                $('input[name=abortoscuantos').prop('required',false);
            }
        });
	});
</script>
	<style>
	.brand-logo {
		    position: absolute;
		    color: #fff;
		    display: inline-block;
		    font-size: 2.1rem;
		    padding: 0;
		    white-space: nowrap;
		}
		#listaservicios li{
			opacity: 0;
		}
		.parallax-container {
			height: 500Spx;
		}
		.relative {
			position: relative;
		}
		#particles-js canvas {
			position: absolute;
			top: 0;
			height: auto;
			z-index: -1;
		}
		.holder {
			background-color: #fff;
		    opacity: 0.7;
		    z-index: 10;
		}
		@media screen and (max-width: 600px) {
			.brand-logo{
				margin: auto;
			}
		}
		/* ----------- logo sidebar ------*/
		.logo-sidebar {
			width: 64px;
			height: 64px;
			margin-left: auto;
			margin-top: auto;
			cursor: pointer;
		}
		/*-------- left sidebar ---------*/
		.main-sidebar {
			background-color: #000;
			overflow: scroll;
		}

		.main-sidebar nav{
			background-color: transparent;
		}

		.nombre-sidebar{
			text-align: center;
			font-weight: bold;
			color: rgb(255, 255, 255);
		}

		.lista-sidebar{
			color: rgb(112, 219, 255);
			width: 100%;
			list-style: none;
			text-align: left;
		}

		.lista-sidebar:hover{
			background-color: rgb(0, 153, 255);
		}

		.boton-logout{
			color: rgb(255, 255, 255);
			border: 3px;
			background-color: rgb(112, 219, 255);
			min-width: 50%;
			height: auto;
			list-style: none;
		}
		/* -------- imagen ------------*/
		.img-sidebar{
			 width: 200px;
			 height: 200px;
			 margin: auto;
			 background-size: cover;
			 display: block;
			 border-radius: 150px;
			 -webkit-border-radius: 150px;
			 -moz-border-radius: 150px;
		}

	</style>
</head>

<body>

<div class="navbar-fixed">
	<nav class="cyan darken-1">
		<div class="nav-wrapper ">
			<div id="main-navbar" class="main-navbar main-navbar-fixed-top">
	              <div class="main-navbar-content">
	                  	<div id="toggle-sidebar" class="icon left">
	                    	<img class="logo-sidebar" alt="menu" src="<?=$this->getSecureImage('logo_negro.png'); ?>" > 
	                  	</div>
	              </div>
	        </div> 
			<a href="/" class="brand-logo center">MAS<span class="indigo-text text-darken-4">Alpha</span></a>

			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<?php if($this->auth->isAuth()) : ?>
					<li><a href="/User/logout">Logout: <?=$this->user->getUsername();?></a></li>
				<?php else : ?>
					<li><a href="/User">Login</a></li>
				<?php endif; ?>
			</ul>
			<ul class="side-nav" id="mobile-demo">
		        <?php if($this->auth->isAuth()) : ?>
					<li><a href="/User/logout">Logout: <?=$this->user->getUsername();?></a></li>
				<?php else : ?>
					<li><a href="/User">Login</a></li>
				<?php endif; ?>
		     </ul>
		</div>
	</nav>
</div>

	
	 <?php if($this->auth->isAuth()) : ?>
<div class="row">
	<div class="right-align">
		<iframe src="http://free.timeanddate.com/clock/i4tc10mo/n162/tlmx4/fn14/fs18/ahr/ftb/pa10/tt0/tw1/tm3/tb4" frameborder="0" width="183" height="64"></iframe>
	</div>
</div>


 	<!-- Esto se llama en todos lados por eso lo puse afuera -->
	<br><br>
	
	          <div id="main-sidebar" class="main-sidebar main-sidebar-left">

	              <div id="main-sidebar-wrapper" class="main-sidebar-wrapper">
	<!-- Hasta aqui termina "esto" -->
	<?php $obj= $this->user->getUserObject(); 
	if ($this->user->getUserType() == 'Doctor'): ?>

          
                  <div class="section">
                      <img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
                      <p class="nombre-sidebar"> Dr. <?=$this->user->getNombreCompleto()?> </p>
                      <p class="nombre-sidebar"> C&eacute;dula: <?=$obj->getCedula() ?> </p>
                  </div>
                  <nav>
                      <ul id="nav-mobile" class="right hide-on-med-and-down">
                          <li class="lista-sidebar"><a href="/Doctor/index" class="active">Inicio</a></li>
                          
                          <li class="lista-sidebar"><a href="/Doctor/examenGeneral" >Examen m&eacute;dico</a></li>
                          
                          <li class="lista-sidebar"><a href="#" >Laboratorio</a></li>
                          
                          <li class="lista-sidebar"><a href="#" >Consulta</a></li>
                          
                          <li class="lista-sidebar"><a href="#" >Gabinete</a></li>
                          
                          <li class="lista-sidebar"><a href="/User/logout" class="boton-logout">Cerrar Sesion</a></li>
                          
                  </nav>
              </div>
          	</div>
      	</div>

  		<?php elseif ($this->user->getUserType() == 'Administrador'): ?>
                  <div class="section">
                      <img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
                      <p class="nombre-sidebar"> Administrador <br><br> <?=$this->user->getNombreCompleto()?> </p>
                  </div>
                  <nav>
                      <ul class="right hide-on-med-and-down">
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">Inicio</a></li>
                          
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">Gesti&oacute;n de usuarios</a></li>
                          
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">Reporte de Proveedores</a></li>
                          
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">Reporte de Clientes</a></li>
                          
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">#####</a></li>
                          
                          <li class="lista-sidebar"><a href="/User/logout" class="boton-logout">Cerrar Sesion</a></li>
                          
                  </nav>
              </div>
          	</div>
      	</div>    
  		<?php elseif ($this->user->getUserType() == 'Cliente'): ?>
                  <div class="section">
                      <img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
                      <p class="nombre-sidebar"> Empresa <b><b> <?=$this->user->getNombreCompleto()?> </p>
                  </div>
                  <nav>
                      <ul class="right hide-on-med-and-down">
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">Inicio</a></li>
                          
                          <li class="lista-sidebar"><a href="/Cliente/solicitudIndividual" class="lista-sidebar">Agendar Cita Individual</a></li>
                          
                          <li class="lista-sidebar"><a href="/Cliente/solicitudGrupal" class="lista-sidebar">Agendar Citas Grupales</a></li>
                          
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">Costos</a></li>
                          
                          <li class="lista-sidebar"><a href="#" class="lista-sidebar">#####</a></li>
                          
                          <li class="lista-sidebar"><a href="/User/logout" class="boton-logout">Cerrar Sesion</a></li>
                          
                  </nav>
              	</div>
          	</div>
      	</div>
  		<?php endif; ?>   
 	<?php endif; echo $this->view; ?>
 	<br><br>
		<footer class="page-footer cyan darken-1">
          <div class="footer-copyright">
            <div class="container">
            © 2015 Copyright Hagane Software
            </div>
          </div>
        </footer>
<script src="/js/simpler-sidebar-1.3.4/dist/jquery.simpler-sidebar.min.js"></script>
<script>
            $(document).ready(function() {
                $('#main-sidebar').simplerSidebar({
                    opener: '#toggle-sidebar',
                    animation: {
                        easing: "easeOutExpo"
                    },
                    sidebar: {
                        align: 'left',
                        width: 360,
                        backgroundColor: 'black',
                        closingLinks: '.close-sb'
                    	
                    }
                    
                });

            });
</script>
<script type="text/javascript">
$(document).ready(function(){
	$('.scrollspy').scrollSpy();
	$('.button-collapse').sideNav({
      menuWidth: 300, // Default is 240
      closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    }
  );
});
</script>
</body>
</html>
