<fieldset>
	<legend>Contacto</legend>
	<form data-abide action="<?= $this->element->getAction(); ?>"
	method="<?= $this->element->getMethod(); ?>">
		<div class="name-field">
			Nombre del contacto<br />
			<?= $this->element->nombre; ?>
			<small class="error">Requerido</small>
		</div>
		<div class="field">
			Teléfono de casa<br />
			<?= $this->element->telcasa; ?>
			<small class="error">Requerido, deber ser un numero</small>
		</div>
		Teléfono de oficina<br />
		<?= $this->element->teloficina; ?>

		Teléfono de celular<br />
		<?= $this->element->telcelular; ?>

		Alumno<br />
		<?= $this->element->idAlumno; ?>

		<?= $this->element->fromreportes; ?>

		<span style="float: right;">
			<?= $this->element->submit; ?>
		</span>
	</form>
</fieldset>
