<div class="large-8 push-4 columns">
    <div class="row">
        <div class="large-6 columns">
            <a href="/Alumno" class="large button secondary expand">
                <div class="row">
                    <div class="large-12 small-4 columns">
                        <img src="/img/alumno.png" />
                    </div>
                    <div class="large-12 small-8 columns">
                        <h3>Alumnos</h3>
                    </div>
                </div>
            </a>
        </div>
        <div class="large-6 columns">
            <a href="/Grupo" class="large button secondary expand">
                <div class="row">
                    <div class="large-12 small-4 columns">
                        <img src="/img/grupo.png" />
                    </div>
                    <div class="large-12 small-8 columns">
                        <h3>Grupos</h3>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="large-6 columns">
            <a href="/Reporte" class="large button secondary expand">
                <div class="row">
                    <div class="large-12 small-4 columns">
                        <img src="/img/reporte.png" />
                    </div>
                    <div class="large-12 small-8 columns">
                        <h3>Reportes</h3>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
<div class="large-4 pull-8 columns">
    <div class="row">
        <div class="large-12 columns">
            <img src="/img/usuario.png" />
            <?php echo $this->idDisplay; ?>
        </div>
    </div>
    <div class="row">
        <div class="large-12 small-12 columns">
            <h3>Recien ingresados</h3>
        </div>
            <div class="large-12 small-6 columns">
                <blockquote>
                <a class="recent" href="<?php echo $this->urllast; ?>"><?php echo $this->nombrelast; ?></a></blockquote>
            </div>
            <div class="large-12 small-6 columns">
                <blockquote>
                <a class="recent" href="<?php echo $this->url; ?>"><?php echo $this->nombre; ?></a></blockquote>
            </div>
    </div>
</div>