    <div class="large-8 push-4 columns">
        <div class="row">
            <div class="large-6 columns">
                <img src="/img/alumno.png" />
                <h3>Alumnos</h3>
            </div>
            <div class="large-6 columns">
                <img src="/img/grupo.png" />
                <h3>Grupos</h3>
            </div>
        </div>
        <div class="row">
            <div class="large-6 columns">
                <img src="/img/reporte.png" />
                <h3>reporte</h3>
            </div>
        </div>
    </div>
    <div class="large-4 pull-8 columns">
        <div class="row">
            <div class="large-12 columns">
                <img src="/img/usuario.png" />
                <?php echo $this->idDisplay; ?>
            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <h3>Recien ingresados</h3>
            </div>
            <div class="row">
                <div class="large-12 small-6 columns">
                    <img src="/img/hombre.png" />
                </div>
                <div class="large-12 small-6 columns">
                    <img src="/img/mujer.png" />
                </div>
            </div>
        </div>
    </div>