<fieldset>
	<legend>Datos Hereditarios</legend>
	<form action="<?= $this->element->getAction(); ?>"
	method="<?= $this->element->getMethod(); ?>">

		<p>Familiares que presenten:</p>

		Alguna alteraci&oacute;n en el lenguaje (si no, dejar en blanco)<br />
		<?= $this->element->lenguaje; ?>

		Alg&uacute;n tipo de retardo cognitivo o intelectual (si no hay, dejar en blanco)<br />
		<?= $this->element->retardo; ?>

		Que hayan presentado alg&uacute;n problema de aprendizaje (si no hay, dejar en blanco)<br />
		<?= $this->element->problemaaprendizajehereditario; ?>

		Alguna patolog&iacute;a cromos&iacute;mica (si no hay, dejar en blanco)<br />
		<?= $this->element->patologiacromosomica; ?>

		Alguna patolog&iacute;a psiqui&aacute;trica (si no hay, dejar en blanco)<br />
		<?= $this->element->patologiapsiquiatrica; ?>


		<?= $this->element->id; ?>

		<span style="float: right;">
			<?= $this->element->submit; ?>
		</span>
	</form>
</fieldset>
