<fieldset>
	<legend>Datos personales</legend>
	<form id="login" action="<?= $this->element->getAction(); ?>"
	method="<?= $this->element->getMethod(); ?>">
		Nombre<br />
		<?= $this->element->nombre; ?>

		Apellido Patrno<br />
		<?= $this->element->apaterno; ?>

		Apellido Materno<br />
		<?= $this->element->amaterno; ?>
		<fieldset>
			<legend>Fecha de nacimiento</legend>
			D&iacute;a<br />
			<?= $this->element->dia; ?>

			Mes<br />
			<?= $this->element->mes; ?>

			A&ntilde;o<br />
			<?= $this->element->anio; ?>
		</fieldset>
		Sexo<br />
		<?= $this->element->sexo; ?>

		Numero de hermanos<br />
		<?= $this->element->numhermanos; ?>

		Lugar en la familia<br />
		<?= $this->element->lugarfam; ?>

		Diagn&oacute;stico<br />
		<?= $this->element->diagnostico; ?>

		Tipo de sangre<br />
		<?= $this->element->tiposangre; ?>

		Nombre del padre<br />
		<?= $this->element->nombrepadre; ?>

		nNombre de la madre<br />
		<?= $this->element->nombremadre; ?>

		Domicilio<br />
		<?= $this->element->domicilio; ?>

		Seguro<br />
		<?= $this->element->seguro; ?>

		Poliza<br />
		<?= $this->element->poliza; ?>

		¿Recibe rehabilitaci&oacute;n del Aprenizaje? (Si no, dejar en blanco)<br />
		<?= $this->element->rehab; ?>

		¿Recibe apoyo psicol&oacute;gico? (Si no, dejar en blanco)<br />
		<?= $this->element->apoyopsico; ?>

		<?= $this->hola ?>
		<span style="float: right;">
			<?= $this->element->submit; ?>
		</span>
	</form>
</fieldset>
