<fieldset>
	<legend>Contacto</legend>
	<form data-abide action="<?= $this->element->getAction(); ?>"
	method="<?= $this->element->getMethod(); ?>">
		<div class="name-field">
			Nombre del contacto<br />
			<?= $this->element->nombre; ?>
			<small class="error">Requerido</small>
		</div>
		<div class="field">
			Especialidad<br />
			<?= $this->element->especialidad; ?>
			<small class="error">Requerido</small>
		</div>
		<div class="field">
			Telefono oficina<br />
			<?= $this->element->teloficina; ?>
			<small class="error">Requerido</small>
		</div>

		<div class="field">
			Telefono celular<br />
			<?= $this->element->telcelular; ?>
			<small class="error">Requerido</small>
		</div>

		Alumno<br />
		<?= $this->element->idAlumno; ?>

		
		<?= $this->element->fromreportes; ?>
		
		<span style="float: right;">
			<?= $this->element->submit; ?>
		</span>
	</form>
</fieldset>
