<fieldset>
	<legend>Medicinas</legend>
	<form data-abide action="<?= $this->element->getAction(); ?>"
	method="<?= $this->element->getMethod(); ?>">
		<div class="name-field">
			Nombre de la medicina<br />
			<?= $this->element->nombre; ?>
			<small class="error">Requerido</small>
		</div>
		<div class="field">
			Fórmula<br />
			<?= $this->element->formula; ?>
			<small class="error">Requerido</small>
		</div>
		<div class="field">
			Frecuencia<br />
			<?= $this->element->frecuencia; ?>
			<small class="error">Requerido</small>
		</div>

		Alumno<br />
		<?= $this->element->idAlumno; ?>

		<span style="float: right;">
			<?= $this->element->submit; ?>
		</span>
	</form>
</fieldset>
