<fieldset>
	<legend>Antecedentes del embarazo</legend>
	<form action="<?= $this->element->getAction(); ?>"
	method="<?= $this->element->getMethod(); ?>">
		¿Embarazo planeado?<br />
		<?= $this->element->embarazoplaneado; ?>

		¿El embarazo fue de alto riesgo?<br />
		<?= $this->element->embarazoriesgoso; ?>

		¿Hubo amenaza de aborto? (Si no, dejar en blanco)<br />
		<?= $this->element->amenazaaborto; ?>

		¿Hubo amenaza de parto prematuro? (Si no, dejar en blanco)<br />
		<?= $this->element->amenazaprematuro; ?>

		¿Tuvo la madre contacto con alguna persona con alguna enfermedad? (Si no, dejar en blanco)<br />
		<?= $this->element->contactoenfermedad; ?>

		¿La madre sufri&oacute; alg&uacute;n accidente durante el embarazo? (Si no, dejar en blanco)<br />
		<?= $this->element->accidenteembarazo; ?>

		<?= $this->element->id; ?>

		<span style="float: right;">
			<?= $this->element->submit; ?>
		</span>
	</form>
</fieldset>
