<div class="large-8 push-4 columns">
	    <div class="button-bar">
                <ul class="button-group">
                  <li><a href="/Alumno/datos/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Datos<br>personales</a></li>
                  <li><a href="/Alumno/antecedentes/id/<?= $this->idalumno; ?>" class="tiny button alta">Antecedentes<br>de embarazo</a></li>
                  <li><a href="/Alumno/prenatales/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Prenatales<br></a></li>
                  <li><a href="/Alumno/perinatales/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Perinatales<br></a></li>
                  <li><a href="/Alumno/posnatales/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Posnatales<br></a></li>
                  <li><a href="/Alumno/hereditario/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Factores<br>hereditarios</a></li>
                </ul>
        </div>
    <?= $this->form; ?>
</div>
