<div class="large-8 push-4 columns">
	<div class="progress large-12 success round"><span class="meter" style="width: 25%"></span></div>
    <div class="button-bar">
        <ul class="button-group">
          <li><span class="tiny button secondary">Datos<br>personales</span></li>
          <li><span class="tiny button secondary">Antecedentes<br>de embarazo</span></li>
          <li><span class="tiny button secondary">Prenatales</span></li>
          <li><span class="tiny button secondary">Perinatales</span></li>
          <li><span class="tiny button secondary">Posnatales</span></li>
        </ul>
        <ul class="button-group">
          <li><span class="tiny button secondary">Factores<br>hereditarios</span></li>
        </ul>
         <?php echo $this->id; ?>

    </div>
</div>
<div class="large-4 pull-8 columns">
    <div class="row">
        <div class="large-12 columns">
            <img src="/img/usuario.png" />
            <?php echo $this->idDisplay; ?>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <h3>Recien ingresados</h3>
        </div>
        <div class="row">
            <div class="large-12 small-6 columns">
                <img class="recien" src="/img/hombre.png" />
            </div>
            <div class="large-12 small-6 columns">
                <img class="recien" src="/img/mujer.png" />
            </div>
        </div>
    </div>
</div>