<div class="large-8 push-4 columns">
	    <div class="button-bar">
                <ul class="button-group">
                  <li><a class="tiny button">Datos<br>personales</a></li>
                  <li><a <?= $this->antecedentes; ?>class="tiny button secondary">Antecedentes<br>de embarazo</a></li>
                  <li><a <?= $this->prenatales; ?>class="tiny button secondary">Prenatales</a></li>
                  <li><a <?= $this->perinatales; ?>class="tiny button secondary">Perinatales</a></li>
                  <li><a <?= $this->posnatales; ?>class="tiny button secondary">Posnatales</a></li>
                  <li><a <?= $this->hereditario; ?>class="tiny button secondary">Factores<br>hereditarios</a></li>
                </ul>
        </div>
	<?= $this->form; ?>
</div>