<div class="large-8 push-4 columns">
    <div class="button-bar">
                <ul class="button-group">
                  <li><a href="<?php echo $this->baseUrl(); ?>/Alumno/datos/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Datos<br>personales</a></li>
                  <li><a href="<?php echo $this->baseUrl(); ?>/Alumno/antecedentes/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Antecedentes<br>de embarazo</a></li>
                  <li><a href="<?php echo $this->baseUrl(); ?>/Alumno/prenatales/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Prenatales<br></a></li>
                  <li><a href="<?php echo $this->baseUrl(); ?>/Alumno/perinatales/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Perinatales<br></a></li>
                  <li><a href="<?php echo $this->baseUrl(); ?>/Alumno/posnatales/id/<?= $this->idalumno; ?>" class="tiny button secondary alta">Posnatales<br></a></li>
                  <li><a href="<?php echo $this->baseUrl(); ?>/Alumno/hereditario/id/<?= $this->idalumno; ?>" class="tiny button alta">Factores<br>hereditarios</a></li>
                </ul>
        </div>
    <?= $this->form; ?>
</div>
