<div class="large-8 push-4 columns" style="padding-left: 15px;">
        <div class="row">
                <div class="large-6 columns panel">
                        <a href="/Alumno/Datos">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="/img/alumno.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta <br> Alumno</h3>
                                        </div>
                                </div>
                        </a> 
                </div>
                <div class="large-6 columns panel">
                        <a href="/Alumno/contactos">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="/img/contacto.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta Contactos de Emergencia</h3>
                                        </div>
                                </div>
                        </a>
                </div>
        </div>
        <div class="row">
                <div class="large-6 columns panel">
                        <a href="/Alumno/medicinas">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="/img/medicinas.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta Medicinas</h3>
                                        </div>
                                </div>
                        </a>
                </div>
                <div class="large-6 columns panel">
                        <a href="/Alumno/Medicos">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="/img/doctor.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta M&eacute;dicos</h3>
                                        </div>
                                </div>
                        </a>
                </div>
        </div>
        <div class="row">
                <div class="large-6 columns panel">
                        <a href="/Alumno/modificar">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="/img/modificar.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Modificación</h3>
                                        </div>
                                </div>
                        </a>
                </div>
                <div class="large-6 columns panel">
                        <a href="/Alumno/hospital">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="/img/hospital.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Hospitalización</h3>
                                        </div>
                                </div>
                        </a>
                </div>
        </div>
</div>
