<div class="large-8 push-4 columns">
<!-- 	<div class="button-bar">
		<ul class="button-group">
		  <li><span class="tiny buttonsecondary">Datos<br>personales</span></li>
		  <li><span class="tiny button secondary">Contactos de<br>emergencia</span></li>
		  <li><span class="tiny button secondary">M&eacute;dicos<br>y medicinas</span></li>
		  <li><span class="tiny button secondary">Antecedentes<br>de embarazo</span></li>
		  <li><span class="tiny button secondary">Prenatales</span></li>
		  <li><span class="tiny button secondary">Perinatales</span></li>
		  <li><span class="tiny button secondary">Posnatales</span></li>
		</ul>
		<ul class="button-group">
		  <li><span class="tiny button secondary">Factores<br>hereditarios</span></li>
		</ul>
	</div> -->
	<div class="progress large-12 success round"><span class="meter" style="width: 12.5%"></span></div>
	<?= $this->form; ?>
</div>
<div class="large-4 pull-8 columns">
    <div class="row">
        <div class="large-12 columns">
            <img src="/img/usuario.png" />
            <?php echo $this->idDisplay; ?>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <h3>Recien ingresados</h3>
        </div>
        <div class="row">
            <div class="large-12 small-6 columns">
                <img class="recien" src="/img/hombre.png" />
            </div>
            <div class="large-12 small-6 columns">
                <img class="recien" src="/img/mujer.png" />
            </div>
        </div>
    </div>
</div>