<div class="large-8 push-4 columns">
    <div class="row">
        <div class="large-6 columns">
            <a href="/Alumno/Datos" class="large button secondary expand">
                <div class="row">
                    <div class="large-12 small-4 columns">
                        <img src="/img/alumno.png" />
                    </div>
                    <div class="large-12 small-8 columns">
                        <h3>Alta Alumno</h3>
                    </div>
                </div>
            </a>
        </div>
        <div class="large-6 columns">
            <a href="/Alumno/contactos" class="large button secondary expand">
                <div class="row">
                    <div class="large-12 small-4 columns">
                        <img src="/img/contacto.png" />
                    </div>
                    <div class="large-12 small-8 columns">
                        <h3>Alta Contactos de emergencia</h3>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="large-6 columns">
            <a href="/Alumno/medicinas" class="large button secondary expand">
                <div class="row">
                    <div class="large-12 small-4 columns">
                        <img src="/img/medicinas.png" />
                    </div>
                    <div class="large-12 small-8 columns">
                        <h3>Alta Medicinas</h3>
                    </div>
                </div>
            </a>
        </div>
        <div class="large-6 columns">
            <a href="/Alumno/Medicos" class="large button secondary expand">
                <div class="row">
                    <div class="large-12 small-4 columns">
                        <img src="/img/doctor.png" />
                    </div>
                    <div class="large-12 small-8 columns">
                        <h3>Alta Medicos</h3>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
