<div class="large-8 push-4 columns">
	<h3>Modificar</h3>
         <?php if (!empty($this->query)){
                    foreach($this->query AS $query) {
                      echo "
                       <div class='small-12 large-6 columns'>
                                <div class='row collapse'>
                                    <div class='small-9 columns'>
                                      <span class='prefix'>".$query['nombre']." ".$query['apaterno']." ".$query['amaterno']."</span>
                                    </div>
                                    <div class='small-3 columns'>
                                      <a href='/Alumno/datos/id/".$query['id']."' class='button prefix'>-></a>
                                    </div>
                                </div>
                        </div>";
                    } 
            } ?>
</div>
