<div class="large-8 push-4 columns">
	    <div class="button-bar">
                <ul class="button-group">
                  <li><a href="/Alumno/datos/id/<?= $this->idalumno; ?>" class="tiny button secondary">Datos<br>personales</a></li>
                  <li><a href="/Alumno/antecedentes/id/<?= $this->idalumno; ?>" class="tiny button secondary">Antecedentes<br>de embarazo</a></li>
                  <li><a href="/Alumno/prenatales/id/<?= $this->idalumno; ?>" class="tiny button secondary">Prenatales</a></li>
                  <li><a href="/Alumno/perinatales/id/<?= $this->idalumno; ?>" class="tiny button secondary">Perinatales</a></li>
                  <li><a href="/Alumno/posnatales/id/<?= $this->idalumno; ?>" class="tiny button secondary">Posnatales</a></li>
                </ul>
                <ul class="button-group">
                  <li><a href="/Alumno/hereditario/id/<?= $this->idalumno; ?>" class="tiny button secondary">Factores<br>hereditarios</a></li>
                </ul>
        </div>
	<h2>Ha terminado el proceso de registro del Alumno.</h2>
</div>
