<div class="large-8 push-4 columns">
    <fieldset>
      <legend>Selecciona un alumno</legend>
    <?= $this->form; ?></fieldset>
    <div class="section-container auto vertical-tabs" data-section="vertical-tabs">
      <section class="active">
        <p class="title" data-section-title><a href="#panel1">Datos Personales</a></p>
        <div class="content" data-section-content>
          <strong><?= $this->query['nombre']." ".$this->query['apaterno']." ".$this->query['amaterno'] ?></strong>
          <br>Nombre:  <?= $this->query['nombre'] ?> 
          <br>Apellido Paterno: <?= $this->query['apaterno'] ?>
          <br>Apellido Materno: <?= $this->query['amaterno'] ?>
          <?php

                $fecha = explode("-", $this->query['fechanacimiento']);     

                $datafromdb['anio'] = $fecha[0];
                $datafromdb['mes'] = $fecha[1];
                $datafromdb['dia'] = $fecha[2];
                 ?>
         <br> Fecha de nacimiento: <?= $datafromdb['dia'] ?> - <?= $datafromdb['mes'] ?> - <?= $datafromdb['anio'] ?>
         <br> Sexo:<?php if($this->query['sexo']== 'm'){
                      echo 'Masculino';
         }else{
                      echo 'Femenino';
         } ?>
         <br> No. de hermanos:<?= $this->query['nohermanos'] ?>
         <br> Lugar que ocupa en la familia el alumno:<?= $this->query['lugarfamilia'] ?>
         <br> Diagnóstico establecido del alumno:<?= $this->query['diagnostico'] ?>
         <br> <?php if($this->query['seguro'] == '')
                    echo '<br>No cuenta con seguro de gastos medicos';
                else
                    echo "<br>Seguro:".$this->query['seguro'] ."<br>Poliza: ".$this->query['poliza'];?>
            <br>Nombre del padre:<?= $this->query['nombrepadre'] ?>
            <br>Nombre de la madre:<?= $this->query['nombremadre'] ?>
            <br>Domicilio:<?= $this->query['domicilio'] ?>
            <br><?php if($this->query['rehab'] == '')
                    echo '<br>No lleva una reahilitación del aprendizaje';
                else
                    echo "<br>Rehabilitación del aprendizaje:".$this->query['seguro'];?>
            <br> <?php if($this->query['apoyopsico'] == '')
                    echo '<br>No tiene apoyo psicológico';
                else
                    echo "<br>Apoyo psicológico:".$this->query['apoyopsico'];?>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel3">Contactos de emergencia</a></p>
        <div class="content" data-section-content>
          <?php 
            if (!empty($this->contacto)){
                    foreach($this->contacto AS $contact) {
                      echo "Nombre:  ".$contact['nombre']."<br />";
                      echo "Teléfono casa:  ".$contact['telcasa']."<br />";
                      echo "Teléfono oficina:  ".$contact['teloficina']."<br />";
                      echo "Teléfono celular:  ".$contact['telcelular']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/contactos/id/<?php echo $this->id; ?>">Agregar contacto de emergencia</a>
          </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel7">Doctores</a></p>
        <div class="content" data-section-content>
          <?php 
            if (!empty($this->medico)){
                    foreach($this->medico AS $medic) {
                      echo "Nombre:  ".$medic['nombre']."<br />";
                      echo "Especialidad:  ".$medic['especialidad']."<br />";
                      echo "Teléfono oficina:  ".$medic['teloficina']."<br />";
                      echo "Teléfono celular:  ".$medic['telcelular']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/medicos/id/<?php echo $this->id; ?>">Agregar Doctor</a>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel8">Medicaciones</a></p>
        <div class="content" data-section-content>
          <?php 
            if (!empty($this->medicina)){
                    foreach($this->medicina AS $medicina) {
                      echo "Nombre:  ".$medicina['nombre']."<br />";
                      echo "Fórmula:  ".$medicina['formula']."<br />";
                      echo "Frecuencia:  ".$medicina['frecuencia']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/medicinas/id/<?php echo $this->id; ?>">Agregar Medicamento</a>
        </div>
      </section>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel9">Hospitalizaci&oacute;n</a></p>
        <div class="content" data-section-content>
          <?php 
            if (!empty($this->hospital)){
                    foreach($this->hospital AS $hospital) {
                      echo "Hospital:  ".$hospital['hospital']."<br />";
                      $fecha = explode("-", $hospital['fechaingreso']);     

                      $datafromdb['anio'] = $fecha[0];
                      $datafromdb['mes'] = $fecha[1];
                      $datafromdb['dia'] = $fecha[2];

                      echo "Fecha de ingreso:  ".$datafromdb['dia']."-".$datafromdb['mes']."-".$datafromdb['anio']."<br />";
                      echo "Causa:  ".$hospital['causa']."<br />";
                      echo "Detalles:  ".$hospital['detalles']."<br />";
                      echo "Tiempo internado:  ".$hospital['tiempo']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/hospital/id/<?php echo $this->id; ?>">Agregar Hospitalizaci&oacute;n</a>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel2">Antecedentes de embarazo</a></p>
        <div class="content" data-section-content>
          <br>Embarazo planeado:<?php if($this->query['embarazoplaneado']== 's'){
                                    echo 'Si';
                       }else{
                                    echo 'No';
                       } ?>
          <br>Tipo de embarazo:<?php if($this->query['embarazoriesgoso']== 's'){
                                    echo 'Riesgoso';
                       }else{
                                    echo 'Sin riesgo';
                       } ?>
          <br><?php if($this->query['amenazaaborto'] == '')
                    echo '<br>No hubo amenaza de aborto';
                else
                    echo "<br>Amenaza de aborto:".$this->query['amenazaaborto'];?>
          <br><?php if($this->query['amenazaprematuro'] == '')
                    echo '<br>No hubo amenaza de nacimiento prematuro';
                else
                    echo "<br>Amenaza de nacimiento prematuro:".$this->query['amenazaprematuro'];?>
          <br><?php if($this->query['contactoenfermedad'] == '')
                    echo '<br>No hubo contacto con alguna persona con alguna enfermedad';
                else
                    echo "<br>Contacto con alguna persona con alguna enfermedad:".$this->query['contactoenfermedad'];?>
          <br><?php if($this->query['accidenteembarazo'] == '')
                    echo '<br>No se sufrió accidente durante el embarazo';
                else
                    echo "<br>Se sufrió el(los) siguiente(s) accidente(s) durante el embarazo:".$this->query['accidenteembarazo'];?>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel3">Prenatales</a></p>
        <div class="content" data-section-content>
          <?php if($this->query['enfermedaddurante'] == '')
                    echo '<br>No hubo enfermedad durante el embarazo';
                else
                    echo "<br>Se sufrió el(los) siguiente(s) accidente(s) durante el embarazo:".$this->query['enfermedaddurante'];?>
          <br><?php if($this->query['sustancias'] == '')
                    echo '<br>La madre no estuvo expuesta a sustancias toxicas';
                else
                    echo "<br>La madre estuvo expuesta a las siguientes sustancias toxicas:".$this->query['sustancias'];?>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel4">Perinatales</a></p>
        <div class="content" data-section-content>
          <br>Nacimiento: <?= $this->query['nacimiento'] ?> 
          <br>Tipo de nacimiento: <?= $this->query['tipodeparto'] ?>
          <br>Tiempo de parto: <?= $this->query['tiempo'] ?>
          <br>Nacimiento múltiple: <?php if($this->query['multiple']== 's'){
                                    echo 'Si';
                       }else{
                                    echo 'No';
                       } ?>
          <br><?php if($this->query['cesarea'] == '')
                    echo '<br>No hubo cesárea';
                else
                    echo "<br>La madre tuvo cesárea, los detalles fueron:".$this->query['cesarea'];?>
          <br><?php if($this->query['anoxia'] == '')
                    echo '<br>No hubo anóxia';
                else
                    echo "<br>Hubo Anóxia con los siguientes detalles:".$this->query['anoxia'];?>
          <br><?php if($this->query['hipoxia'] == '')
                    echo '<br>No hubo hipóxia';
                else
                    echo "<br>Hubo hipóxia con los siguientes detalles:".$this->query['hipoxia'];?>
          <br><?php if($this->query['sufrimientofetal'] == '')
                    echo '<br>No hubo sufrimiento fetal';
                else
                    echo "<br>Hubo sufrimiento fetal con los siguientes detalles:".$this->query['sufrimientofetal'];?>
          <br><?php if($this->query['traumaobstetrico'] == '')
                    echo '<br>No hubo trauma obstétrico';
                else
                    echo "<br>Hubo trauma obstétrico con los siguientes detalles:".$this->query['traumaobstetrico'];?>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel5">Posnatales</a></p>
        <div class="content" data-section-content>
          <br>Lloró al nacer: <?php if($this->query['lloro']== 's'){
                                    echo 'Si';
                       }else{
                                    echo 'No';
                       } ?> 
          <br>Le dieron de alta junto a su madre: <?php if($this->query['alta']== 's'){
                                    echo 'Si';
                       }else{
                                    echo 'No';
                       } ?> 
          <br><?php if($this->query['cuidadosintensivos'] == '')
                    echo '<br>No requirió de cuidados intensivos';
                else
                    echo "<br>Requirió de cuidados intensivos. Detalles: ".$this->query['cuidadosintensivos'];?>
          <br><?php if($this->query['problemasalimentacion'] == '')
                    echo '<br>No tuvo problemas de alimentación';
                else
                    echo "<br>Tuvo los siguientes problemas de alimentación: ".$this->query['problemasalimentacion'];?>
          <br><?php if($this->query['traumatismos'] == '')
                    echo '<br>No sufrió traumatismos';
                else
                    echo "<br>Sufrió los siguientes traumatismos:".$this->query['traumatismos'];?>
          <br><?php if($this->query['infeccionneuro'] == '')
                    echo '<br>No tuvo infecciones que afectaran el área neurológica';
                else
                    echo "<br>Tuvo las siguientes infecciones que afectaron el área neurológica: ".$this->query['infeccionneuro'];?>
          <br><?php if($this->query['alergias'] == '')
                    echo '<br>No tiene alergias ';
                else
                    echo "<br>Tiene las siguientes alergias: ".$this->query['alergias'];?>
          <br><?php if($this->query['convulsiones'] == '')
                    echo '<br>No sufre de convulsiones';
                else
                    echo "<br>Sufre de convulsiones con los siguientes detalles: ".$this->query['convulsiones'];?>
          <br><?php if($this->query['audicion'] == '')
                    echo '<br>No posee problemas de audición';
                else
                    echo "<br>Posee los siguientes problemas de audición: ".$this->query['audicion'];?>
          <br><?php if($this->query['vision'] == '')
                    echo '<br>No posee problemas de visión';
                else
                    echo "<br>Posee los siguientes problemas de visión: ".$this->query['vision'];?>
          <br><?php if($this->query['otros'] == '')
                    echo '<br>';
                else
                    echo "<br>Posee los siguientes problemas adicionales: ".$this->query['otros'];?>
        </div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel6">Factores hereditarios</a></p>
        <div class="content" data-section-content>
          <br><?php if($this->query['lenguaje'] == '')
                    echo '<br> No hay registros de alteración en el lenguaje';
                else
                    echo "<br>Se registraron las alteraciones en el lenguaje siguientes: ".$this->query['lenguaje'];?>
          <br><?php if($this->query['retardo'] == '')
                    echo '<br>No hay registros de retardo cognitivo o intelectual';
                else
                    echo "<br>Se registraron los siguientes retardos cognitivos o intelectuales: ".$this->query['retardo'];?>
          <br><?php if($this->query['problemaaprendizajehereditario'] == '')
                    echo '<br>No hay registro de problemas de aprendizaje';
                else
                    echo "<br>Se poseen registro de los siguienes problemas de aprendizaje: ".$this->query['problemaaprendizajehereditario'];?>
          <br><?php if($this->query['patologiacromosomica'] == '')
                    echo '<br>No hay registro de alguna patología cromosómica';
                else
                    echo "<br>Se poseen las siguienes patologías cromosómicas: ".$this->query['patologiacromosomica'];?>
          <br><?php if($this->query['patologiapsiquiatrica'] == '')
                    echo '<br>No hay registro de patología psiquiátrica';
                else
                    echo "<br>Se registraron las siguientes patologías psiquiátrica: ".$this->query['patologiapsiquiatrica'];?>
        </div>
      </section>
    </div>
</div>
