<div class="large-8 push-4 columns">
  <style type="text/css" scoped>
  .radiobtn{
    padding: 6px 6px; 
    margin: 0;
  }
  </style>
    <fieldset>
      <legend>Selecciona un alumno</legend>
    <?= $this->form; ?></fieldset>
    <div class="section-container auto vertical-tabs" data-section="vertical-tabs">
      <section class="active">
        <p class="title" data-section-title><a href="#panel1">Datos Personales</a></p>
        <div class="content" data-section-content><p>
          <h3><?= $this->query['nombre']." ".$this->query['apaterno']." ".$this->query['amaterno'] ?></h3>
          <br>Nombre:  <?= $this->query['nombre'] ?> 
          <br>Apellido Paterno: <?= $this->query['apaterno'] ?>
          <br>Apellido Materno: <?= $this->query['amaterno'] ?>
          <?php

                $fecha = explode("-", $this->query['fechanacimiento']);     

                $datafromdb['anio'] = $fecha[0];
                $datafromdb['mes'] = $fecha[1];
                $datafromdb['dia'] = $fecha[2];
                 ?>
         <br> Fecha de nacimiento: <?= $datafromdb['dia'] ?> - <?= $datafromdb['mes'] ?> - <?= $datafromdb['anio'] ?>
         <br> Sexo:<?php if($this->query['sexo']== 'm'){
                      echo 'Masculino';
         }else{
                      echo 'Femenino';
         } ?>
         <br> No. de hermanos:<?= $this->query['nohermanos'] ?>
         <br> Lugar que ocupa en la familia el alumno:<?= $this->query['lugarfamilia'] ?>
         <br> Diagnóstico establecido del alumno:<?= $this->query['diagnostico'] ?>

         <br>Nombre del padre:<?= $this->query['nombrepadre'] ?>
         <br>Nombre de la madre:<?= $this->query['nombremadre'] ?>
         <br>Domicilio:<?= $this->query['domicilio'] ?>
            <br> <?php if($this->query['seguro'] == '')
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>No cuenta con seguro de gastos medicos</div>";
                else
                    echo "<br>Seguro:".$this->query['seguro'] ."<br>Poliza: ".$this->query['poliza'];?>
            
            <br><?php if($this->query['rehab'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No lleva una reahilitación del aprendizaje</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Rehabilitación del aprendizaje:".$this->query['seguro']."</div>";?>
            <br> <?php if($this->query['apoyopsico'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No tiene apoyo psicológico</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Apoyo psicológico:".$this->query['apoyopsico']."</div>";?>
                  <br>
        </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel3">Contactos de emergencia</a></p>
        <div class="content" data-section-content><p>
          <?php 
            if (!empty($this->contacto)){
                    foreach($this->contacto AS $contact) {
                      echo "Nombre:  ".$contact['nombre']."<br />";
                      echo "Teléfono casa:  ".$contact['telcasa']."<br />";
                      echo "Teléfono oficina:  ".$contact['teloficina']."<br />";
                      echo "Teléfono celular:  ".$contact['telcelular']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/contactos/id/<?php echo $this->id; ?>">Agregar contacto de emergencia</a>
            <br>
          </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel7">Doctores</a></p>
        <div class="content" data-section-content><p>
          <?php 
            if (!empty($this->medico)){
                    foreach($this->medico AS $medic) {
                      echo "Nombre:  ".$medic['nombre']."<br />";
                      echo "Especialidad:  ".$medic['especialidad']."<br />";
                      echo "Teléfono oficina:  ".$medic['teloficina']."<br />";
                      echo "Teléfono celular:  ".$medic['telcelular']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/medicos/id/<?php echo $this->id; ?>">Agregar Doctor</a>
            <br>
        </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel8">Medicaciones</a></p>
        <div class="content" data-section-content><p>
          <?php 
            if (!empty($this->medicina)){
                    foreach($this->medicina AS $medicina) {
                      echo "Nombre:  ".$medicina['nombre']."<br />";
                      echo "Fórmula:  ".$medicina['formula']."<br />";
                      echo "Frecuencia:  ".$medicina['frecuencia']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/medicinas/id/<?php echo $this->id; ?>">Agregar Medicamento</a>
            <br>
        </p></div>
      </section>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel9">Hospitalizaci&oacute;n</a></p>
        <div class="content" data-section-content><p>
          <?php 
            if (!empty($this->hospital)){
                    foreach($this->hospital AS $hospital) {
                      echo "Hospital:  ".$hospital['hospital']."<br />";
                      $fecha = explode("-", $hospital['fechaingreso']);     

                      $datafromdb['anio'] = $fecha[0];
                      $datafromdb['mes'] = $fecha[1];
                      $datafromdb['dia'] = $fecha[2];

                      echo "Fecha de ingreso:  ".$datafromdb['dia']."-".$datafromdb['mes']."-".$datafromdb['anio']."<br />";
                      echo "Causa:  ".$hospital['causa']."<br />";
                      echo "Detalles:  ".$hospital['detalles']."<br />";
                      echo "Tiempo internado:  ".$hospital['tiempo']."<br /><br />";
                    } 
            }
            ?>
            <a class="button" href="/Alumno/hospital/id/<?php echo $this->id; ?>">Agregar Hospitalizaci&oacute;n</a>
            <br>
        </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel2">Antecedentes de embarazo</a></p>
        <div class="content" data-section-content><p>
          <br><?php if($this->query['embarazoplaneado']== 's'){
                                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">Embarazo planeado: Si</div>';
                       }else{
                                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Embarazo planeado: No</div>";
                       } ?>
          <br><?php if($this->query['embarazoriesgoso']== 's'){
                                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Tipo de embarazo: Riesgoso</div>";
                       }else{
                                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">Tipo de embarazo: Sin riesgo</div>';
                       } ?>
          <br><?php if($this->query['amenazaaborto'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo amenaza de aborto</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Amenaza de aborto:".$this->query['amenazaaborto']."</div>";?>
          <br><?php if($this->query['amenazaprematuro'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo amenaza de nacimiento prematuro</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Amenaza de nacimiento prematuro:".$this->query['amenazaprematuro']."</div>";?>
          <br><?php if($this->query['contactoenfermedad'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo contacto con alguna persona con alguna enfermedad</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Contacto con alguna persona con alguna enfermedad:".$this->query['contactoenfermedad']."</div>";?>
          <br><?php if($this->query['accidenteembarazo'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No se sufrió accidente durante el embarazo</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Se sufrió el(los) siguiente(s) accidente(s) durante el embarazo:".$this->query['accidenteembarazo']."</div>";?>
                  <br>
        </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel3">Prenatales</a></p>
        <div class="content" data-section-content><p>
          <?php if($this->query['enfermedaddurante'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo enfermedad durante el embarazo</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Se sufrió el(los) siguiente(s) accidente(s) durante el embarazo:".$this->query['enfermedaddurante']."</div>";?>
          <br><?php if($this->query['sustancias'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">La madre no estuvo expuesta a sustancias toxicas</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>La madre estuvo expuesta a las siguientes sustancias toxicas:".$this->query['sustancias']."</div>";?>
                  <br>
        </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel4">Perinatales</a></p>
        <div class="content" data-section-content><p>
          <br>Nacimiento: <?= $this->query['nacimiento'] ?> 
          <br>Tipo de nacimiento: <?= $this->query['tipodeparto'] ?>
          <br>Tiempo de parto: <?= $this->query['tiempo'] ?>
          <br><?php if($this->query['multiple']== 's'){
                                    echo '<div class="panel radiobtn" style="background-color: #ffe0da;">Nacimiento múltiple: Si</div>';
                       }else{
                                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">Nacimiento múltiple: No</div>';
                       } ?>
          <br><?php if($this->query['cesarea'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo cesárea</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>La madre tuvo cesárea, los detalles fueron:".$this->query['cesarea']."</div>";?>
          <br><?php if($this->query['anoxia'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo anóxia</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Hubo Anóxia con los siguientes detalles:".$this->query['anoxia']."</div>";?>
          <br><?php if($this->query['hipoxia'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo hipóxia</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Hubo hipóxia con los siguientes detalles:".$this->query['hipoxia']."</div>";?>
          <br><?php if($this->query['sufrimientofetal'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo sufrimiento fetal</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Hubo sufrimiento fetal con los siguientes detalles:".$this->query['sufrimientofetal']."</div>";?>
          <br><?php if($this->query['traumaobstetrico'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hubo trauma obstétrico</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Hubo trauma obstétrico con los siguientes detalles:".$this->query['traumaobstetrico']."</div>";?>
                 <br>
        </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel5">Posnatales</a></p>
        <div class="content" data-section-content><p>
          <br><?php if($this->query['lloro']== 's'){
                                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">Lloró al nacer: Si</div>';
                       }else{
                                    echo '<div class="panel radiobtn" style="background-color: #ffe0da;">Lloró al nacer: No</div>';
                       } ?> 
          <br><?php if($this->query['alta']== 's'){
                                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">Le dieron de alta junto a su madre: Si</div>';
                       }else{
                                    echo '<div class="panel radiobtn" style="background-color: #ffe0da;">Le dieron de alta junto a su madre: No</div>';
                       } ?> 
          <br><?php if($this->query['cuidadosintensivos'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No requirió de cuidados intensivos</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Requirió de cuidados intensivos. Detalles: ".$this->query['cuidadosintensivos']."</div>";?>
          <br><?php if($this->query['problemasalimentacion'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No tuvo problemas de alimentación</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Tuvo los siguientes problemas de alimentación: ".$this->query['problemasalimentacion']."</div>";?>
          <br><?php if($this->query['traumatismos'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No sufrió traumatismos</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Sufrió los siguientes traumatismos:".$this->query['traumatismos']."</div>";?>
          <br><?php if($this->query['infeccionneuro'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No tuvo infecciones que afectaran el área neurológica</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Tuvo las siguientes infecciones que afectaron el área neurológica: ".$this->query['infeccionneuro']."</div>";?>
          <br><?php if($this->query['alergias'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No tiene alergias</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Tiene las siguientes alergias: ".$this->query['alergias']."</div>";?>
          <br><?php if($this->query['convulsiones'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No sufre de convulsiones</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Sufre de convulsiones con los siguientes detalles: ".$this->query['convulsiones']."</div>";?>
          <br><?php if($this->query['audicion'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No posee problemas de audición</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Posee los siguientes problemas de audición: ".$this->query['audicion']."</div>";?>
          <br><?php if($this->query['vision'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No posee problemas de visión</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Posee los siguientes problemas de visión: ".$this->query['vision']."</div>";?>
          <br><?php if($this->query['otros'] == '')
                    echo '';
                else
                    echo "<br><div class='panel radiobtn' style='background-color: #ffe0da;'>Posee los siguientes problemas adicionales: ".$this->query['otros']."</div>";?>
                  <br>
        </p></div>
      </section>
      <section>
        <p class="title" data-section-title><a href="#panel6">Factores hereditarios</a></p>
        <div class="content" data-section-content><p>
          <br><?php if($this->query['lenguaje'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hay registros de alteración en el lenguaje</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Se registraron las alteraciones en el lenguaje siguientes: ".$this->query['lenguaje']."</div>";?>
          <br><?php if($this->query['retardo'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hay registros de retardo cognitivo o intelectual</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Se registraron los siguientes retardos cognitivos o intelectuales: ".$this->query['retardo']."</div>";?>
          <br><?php if($this->query['problemaaprendizajehereditario'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hay registro de problemas de aprendizaje</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Se poseen registro de los siguienes problemas de aprendizaje: ".$this->query['problemaaprendizajehereditario']."</div>";?>
          <br><?php if($this->query['patologiacromosomica'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hay registro de alguna patología cromosómica</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Se poseen las siguienes patologías cromosómicas: ".$this->query['patologiacromosomica']."</div>";?>
          <br><?php if($this->query['patologiapsiquiatrica'] == '')
                    echo '<div class="panel radiobtn" style="background-color: #d3ffce;">No hay registro de patología psiquiátrica</div>';
                else
                    echo "<div class='panel radiobtn' style='background-color: #ffe0da;'>Se registraron las siguientes patologías psiquiátrica: ".$this->query['patologiapsiquiatrica']."</div>";?>
                  <br>
        </p></div>
      </section>
    </div>
</div>
