<br /><br />
<div id="view-content">
	<div class="large-6 push-6 center columns">
	<?php echo $this->form; ?>
	</div>
	<div class="large-6 pull-6 columns">
		<div class="row">
			<div class="large-6 small-6 columns">
			<img style="float:left;" src="<?php echo $this->baseUrl(); ?>/img/logoudem.png" />
			</div>
			<div class="large-6 small-6 columns">
			<img style="float:right;" src="<?php echo $this->baseUrl(); ?>/img/logopisye.png" />
			</div>
		</div>
	</div>
</div>