<html>
<head>
	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pisye</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/foundation.css" />

    <script src="/js/vendor/modernizr.js"></script>
    <script src="/js/vendor/jquery.js"></script>
</head>
<body>

<div class="headerdiv">
    <div class="large-12 columns header" style="text-align: center;">

    </div>
    <div class="large-12 columns menudiv">
        <div class="row">
            <div class="large-3 medium-3 small-12 columns">
                <a href="/info/alumno/lista">Alumnos</a>
            </div>
            <div class="large-3 medium-3 small-12 columns">
                <a href="/info/clase/lista">Clases</a>
            </div>
            <div class="large-3 medium-3 small-12 columns">
                <a href="/info/maestro/lista">Maestro</a>
            </div>
            <div class="large-3 medium-3 small-12 columns">
                <a href="/info/calificacion/lista">Calificaciones</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
<?php if($this->zfcUserIdentity()) :?>
    <div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
    <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
    <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('panelcontrol'); ?>">Menú</a>
    <div style="clear:both;"></div>
<?php endif; ?>
</div>

<?php echo $this->content; ?>


    <script src="/js/foundation.min.js"></script>
    <script src="/js/foundation/foundation.abide.js"></script>
    <script>
    $(document).foundation({
        abide : {
          patterns: {
            alphanumesp: /^[a-zA-Z0-9áéíóúÁÉÍÓÚÑñüÜ (),.#@!-:$&%*]+$/
          }
        }
      });
    </script>

</body>
</html>
