<style type="text/css">
	table.boleta td{
		padding: 5px;
	}
</style>
<div class="container">
	<div class="row">
	<p>Boleta de calificaciones PISYE</p>
	<h4>
		<?=$this->boletas[0]['anombre']?> <?=$this->boletas[0]['apellido_paterno']?> <?=$this->boletas[0]['apellido_materno']?>
	</h4>
	<?php foreach ($this->boletas as $boleta) : ?>
		<div class="col s12 m3">
			<div class="card deep-orange darken-4 white-text" style="padding: 12px;">
				<span class="card-title"><?=$boleta['cnombre']?></span>
				<div class="card-action">
					<table class="boleta">
						<tr>
							<td>parcial1</td><td><?=$boleta['parcial1']?></td>
						<tr>
							<td>parcial2</td><td><?=$boleta['parcial2']?></td>
						</tr>
						<tr>
							<td>participacion</td><td><?=$boleta['participacion']?></td>
						</tr>
						<tr>
							<td>puntualidad</td><td><?=$boleta['puntualidad']?></td>
						</tr>
						<tr>
							<td>disposicion</td><td><?=$boleta['disposicion']?></td>
						</tr>
						<tr>
							<td>tareas</td><td><?=$boleta['tareas']?></td>
						</tr>
						<tr>
							<td>observaciones</td><td><?=$boleta['observaciones']?></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<?php endforeach; ?>
	</div>
</div>