<div class="container">
	<div class="row">
	<?php foreach ($this->clases as $clase) : ?>
		<div class="col s12 m3">
			<div class="card deep-orange darken-4">
				<div class="card-content white-text">
					<span class="card-title"><?=$clase['nombre']?></span>
					<p><?=$clase['descripcion']?></p>
				</div>
				<div class="card-action">
					<a href="/Admin/lista?claseid=<?=$clase['pcid']?>">Ver Alumnos</a>
				</div>
			</div>
		</div>
		<?php endforeach; ?>
	</div>
</div>
