<section id="pagecontent" layout="row" flex ng-controller="AdminClientesController">
	<h3>Panel Administrador</h3>
	<md-card>
		<img ng-src="{{imagePath}}" class="md-card-image">
		<md-card-content>
			<h2 class="md-title">Admin</h2>
			<p>
				Admin
			</p>
		</md-card-content>
		<div class="md-actions" layout="row" layout-align="end center">
			<md-button>Action 1</md-button>
			<md-button>Action 2</md-button>
		</div>
	</md-card>
</section>