<fieldset>
	<legend>Datos personales</legend>
	<form data-abide action="<?= $this->element->getAction(); ?>"
	method="<?= $this->element->getMethod(); ?>">
	<div class="name-field">
		Nombre<br />
		<?= $this->element->nombre; ?>
		<small class="error">Requerido</small>
	</div>
	<div class="field">
		Apellido Paterno<br />
		<?= $this->element->apaterno; ?>
		<small class="error">Requerido</small>
	</div>
	<div class="field">
		Apellido Materno<br />
		<?= $this->element->amaterno; ?>
		<small class="error">Requerido</small>
	</div>
		<fieldset>
			<legend>Fecha de nacimiento</legend>
			<div class="field">
				D&iacute;a<br />
				<?= $this->element->dia; ?>
				<small class="error">Requerido, deber ser un numero</small>
			</div>
			<div class="field">
				Mes<br />
				<?= $this->element->mes; ?>
				<small class="error">Requerido, deber ser un numero</small>
			</div>
			<div class="field">
				A&ntilde;o<br />
				<?= $this->element->anio; ?>
				<small class="error">Requerido, deber ser un numero</small>
			</div>
		</fieldset>
		<div class="field">
			Sexo<br />
			<?= $this->element->sexo; ?>
			<small class="error">Requerido</small>
		</div>
		<div class="field">
			N&uacute;mero de hermanos<br />
			<?= $this->element->numhermanos; ?>
			<small class="error">Requerido, deber ser un numero</small>
		</div>
		<div class="field">
			Lugar en la familia<br />
			<?= $this->element->lugarfam; ?>
			<small class="error">Requerido, deber ser un numero</small>
		</div>

		Diagn&oacute;stico<br />
		<?= $this->element->diagnostico; ?>

		Tipo de sangre<br />
		<?= $this->element->tiposangre; ?>

		Nombre del padre<br />
		<?= $this->element->nombrepadre; ?>

		Nombre de la madre<br />
		<?= $this->element->nombremadre; ?>

		Domicilio<br />
		<?= $this->element->domicilio; ?>

		Seguro<br />
		<?= $this->element->seguro; ?>

		P&oacute;liza<br />
		<?= $this->element->poliza; ?>

		Grupo<br />
		<?= $this->element->grupo; ?>

		¿Recibe rehabilitaci&oacute;n de Aprendizaje? (Si no, dejar en blanco)<br />
		<?= $this->element->rehab; ?>

		¿Recibe apoyo psicol&oacute;gico? (Si no, dejar en blanco)<br />
		<?= $this->element->apoyopsico; ?>

		<?= $this->element->id; ?>

		<span style="float: right;">
			<?= $this->element->submit; ?>
		</span>
	</form>
</fieldset>