<div class="large-8 push-4 columns" style="padding-left: 15px;">
        <div class="row">
                <div class="large-6 columns panel">
                        <a href="<?php echo $this->baseUrl(); ?>/Alumno/Datos">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="<?php echo $this->baseUrl(); ?>/img/alumno.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta <br> Alumno</h3>
                                        </div>
                                </div>
                        </a> 
                </div>
                <div class="large-6 columns panel">
                        <a href="<?php echo $this->baseUrl(); ?>/Alumno/contactos">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="<?php echo $this->baseUrl(); ?>/img/contacto.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta Contactos de Emergencia</h3>
                                        </div>
                                </div>
                        </a>
                </div>
        </div>
        <div class="row">
                <div class="large-6 columns panel">
                        <a href="<?php echo $this->baseUrl(); ?>/Alumno/medicinas">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="<?php echo $this->baseUrl(); ?>/img/medicinas.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta Medicinas</h3>
                                        </div>
                                </div>
                        </a>
                </div>
                <div class="large-6 columns panel">
                        <a href="<?php echo $this->baseUrl(); ?>/Alumno/Medicos">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="<?php echo $this->baseUrl(); ?>/img/doctor.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Alta M&eacute;dicos</h3>
                                        </div>
                                </div>
                        </a>
                </div>
        </div>
        <div class="row">
                <div class="large-6 columns panel">
                        <a href="<?php echo $this->baseUrl(); ?>/Alumno/modificar">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="<?php echo $this->baseUrl(); ?>/img/modificar.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Modificación</h3>
                                        </div>
                                </div>
                        </a>
                </div>
                <div class="large-6 columns panel">
                        <a href="<?php echo $this->baseUrl(); ?>/Alumno/hospital">
                                <div class="row">
                                        <div class="large-3 small-3 columns">
                                                <img src="<?php echo $this->baseUrl(); ?>/img/hospital.png" />
                                        </div>
                                        <div class="large-9 small-9 columns">
                                                <h3>Hospitalización</h3>
                                        </div>
                                </div>
                        </a>
                </div>
        </div>
</div>
