<section class="register">
<h2>Login</h2>
<?php if ($this->error): ?>
<p class="error">
 There were one or more issues with your submission.
Please correct them as
 indicated below.
</p>
<?php endif ?>

<?php
        $form = $this->form;
        $form->prepare();

        $form->setAttribute('action', $this->url(NULL, array('controller'=>'Login', 'action' => 'process')));
        echo $this->form()->openTag($form);
?>

<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('username')); ?></dt>
<dd><?php echo $this->formElement($form->get('username')); ?></dd>
<dt><?php echo $this->formLabel($form->get('password')); ?></dt>
<dd><?php echo $this->formElement($form->get('password')); ?></dd>
<?php echo $this->formElement($form->get('submit')); ?></dd>
</dl>
<?php echo $this->form()->closeTag() ?>
</section>