<?php echo $this->doctype() ?>
<html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Historial Cl&iacute;nico</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/foundation.css')->appendStylesheet($this->baseUrl().'/css/historial.css'); ?>
  <?php //echo $this->headScript()->appendFile( "/js/vendor/custom.modernizr.js", $type = 'text/javascript' ); ?>

</head>
<body>
  <div style="margin-top:5px;" id="content" class="row">
    <?php echo $this->layout()->content ?>
  </div>
  <div id="footer"  class="row" style="max-width: 100% !important;">
    <div class="large-12 small-12 small-centered columns">
      <img style="float:left;" src="<?php echo $this->baseUrl(); ?>/img/logoudem.png" /><img style="float:right;" src="<?php echo $this->baseUrl(); ?>/img/logopisye.png" />
    </div>
  </div>
  <script>
  document.write('<script src=' +
  ('__proto__' in {} ? <?php echo $this->baseUrl().'/js/vendor/zepto'; ?> : <?php echo $this->baseUrl().'/js/vendor/jquery'; ?>) +
  '.js><\/script>')
  </script>

  <?php echo $this->headScript()->appendFile($this->baseUrl()."/js/vendor/custom.modernizr.js", $type = 'text/javascript')
                                ->appendFile($this->baseUrl()."/js/foundation.min.js", $type = 'text/javascript')
                                ->appendFile($this->baseUrl()."/js/foundation/foundation.topbar.js", $type = 'text/javascript'); ?>

  <script>
    $(document).foundation();
  </script>
  <script>
    window.print();
    location.href="<?php echo $this->baseUrl(); ?>/Reporte/general/id/"+<?= $this->id ?>;
  </script>
       

</body>
</html>