<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Historial Cl&iacute;nico</title>

  <link rel="stylesheet" href="css/foundation.css">
  <?php echo $this->headLink()->appendStylesheet('/css/historial.css') ?>
  <script src="js/vendor/custom.modernizr.js"></script>
</head>
<body>
  <div id="header" class="row">
    <div class="large-12 columns">
      <h2>Historial Cl&iacute;nico Pysie</h2>
      <p>Bienvenido</p>
      <nav class="top-bar">
        <ul class="title-area">
          <!-- Title Area -->
          <li class="name"></li>
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Left Nav Section -->
          <ul class="left">
            <li class="has-dropdown"><a href="#">Sistemas UdeM</a>
              <ul class="dropdown">
                <li><a href="#">Calificaciones</a></li>
                <li><a href="#">Portal L&uacute;minis</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="active"><a href="#">Alumnos</a></li>
            <li class="divider"></li>
            <li class="active"><a href="#">Grupos</a></li>
          </ul>

          <!-- Right Nav Section -->
          <ul class="right">
            <li class="has-form">
              <form>
                <div class="row collapse">
                  <div class="small-8 columns">
                    <input type="text" placeholder="Buscar Alumno">
                  </div>
                  <div class="small-4 columns">
                    <a href="#" class="button">Buscar</a>
                  </div>
                </div>
              </form>
            </li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <div id="content" class="row">
    <?php echo $this->layout()->content ?>
  </div>
  <div id="footer" class="row">
    <div class="large-3 small-8 small-centered columns">
      <p>Erick Castillo de la Garza<img style="float:right;" src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
    </div>
  </div>
  <script>
  document.write('<script src=' +
  ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
  '.js><\/script>')
  </script>
  <script src="js/foundation.min.js"></script>
  <script src="js/foundation/foundation.topbar.js"></script>

  <script>
    $(document).foundation();
  </script>
</body>
</html>