<?php echo $this->doctype() ?>
<html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Historial Cl&iacute;nico</title>

  <?php echo $this->headLink()->appendStylesheet('/css/foundation.css')->appendStylesheet('/css/historial.css'); ?>
  <?php //echo $this->headScript()->appendFile( "/js/vendor/custom.modernizr.js", $type = 'text/javascript' ); ?>
<script>
function showResult(str)
{
if (str.length==0)
  { 
  document.getElementById("livesearch").innerHTML="";
  document.getElementById("livesearch").style.border="0px";
  return;
  }
if (window.XMLHttpRequest)
  {// code for IE7+, Firefox, Chrome, Opera, Safari
  xmlhttp=new XMLHttpRequest();
  }
else
  {// code for IE6, IE5
  xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
xmlhttp.onreadystatechange=function()
  {
  if (xmlhttp.readyState==4 && xmlhttp.status==200)
    {
    document.getElementById("livesearch").innerHTML=xmlhttp.responseText;
    document.getElementById("livesearch").style.border="1px solid #000";
    }
  }
xmlhttp.open("GET","/alumno/livesearch/?q="+str,true);
xmlhttp.send();
}
</script>

</head>
<body>
  <div id="header" class="row">
    <div class="large-12 columns">
      <div class="row">
        <div class="large-2 small-7 columns">
          <a href="/"><img src="/img/logoblancop.png" /></a>
        </div>
        <div class="large-10 small-5 columns">
          <h2>Historial Cl&iacute;nico Pisye</h2>
          <p>Bienvenido</p>
        </div>
      </div>
      <nav class="top-bar">
        <ul class="title-area">
          <!-- Title Area -->
          <li class="name"></li>
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Left Nav Section -->
          <ul class="left">
            <li class="has-dropdown"><a href="#">Sistemas UdeM</a>
              <ul class="dropdown">
                <li><a href="#">Calificaciones</a></li>
                <li><a href="http://portal.udem.edu.mx/cp/home/loginf">Portal L&uacute;minis</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="active"><a href="/Alumno">Alumnos</a></li>
            <li class="divider"></li>
            <li class="active"><a href="/Grupo">Grupos</a></li>
            <li class="divider"></li>
            <li class="active"><a href="/Reporte">Reportes</a></li>
          </ul>

          <!-- Right Nav Section -->
          <ul class="right">
            <li class="has-form">
              <form>
                <div class="row collapse">
                  <div class="small-8 columns">
                    <input type="text" placeholder="Buscar Alumno" onkeyup="showResult(this.value)">

                  </div>
                  <div class="small-4 columns">
                    <a href="#" class="button">Buscar</a>
                  </div>
                </div>    
              </form>
            </li>
          </ul>
        </section>
      </nav>
      <div id="livesearch" ></div>
    </div>
  </div>
  <div id="content" class="row">
    <?php echo $this->layout()->content ?>
  </div>
  <div id="footer" class="row">
    <div class="large-3 small-8 small-centered columns">
      <p>Erick Castillo de la Garza<img style="float:right;" src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
    </div>
  </div>
  <script>
  document.write('<script src=' +
  ('__proto__' in {} ? '/js/vendor/zepto' : '/js/vendor/jquery') +
  '.js><\/script>')
  </script>

  <?php echo $this->headScript()->appendFile("/js/vendor/custom.modernizr.js", $type = 'text/javascript')
                                ->appendFile("/js/foundation.min.js", $type = 'text/javascript')
                                ->appendFile("/js/foundation/foundation.topbar.js", $type = 'text/javascript'); ?>

  <script>
    $(document).foundation();
  </script>
</body>
</html>