<div class="row">
	<div class="col s12 m6">
		<h2 class="col s12 header"><?=$this->alumno['cnombre']?></h2>
		<p class="promo-caption"><?=$this->alumno['anombre']?> <?=$this->alumno['apellido_paterno']?> <?=$this->alumno['apellido_materno']?></p>
	</div>
</div>
<div class="row">
	<div class="col s12 m6">
	<form method="post" action="/Maestro/calificar?claseid=<?=$this->alumno['pcid']?>&alumnoid=<?=$this->alumno['aid']?>">
		<table class="hoverable">
		<thead>
		  <tr>
		      <th >Parcial 1</th>
		      <th >Parcial 2</th>
		      <th ></th>
		  </tr>
		</thead>
		<tbody>
		  <tr>
		    <td><input type="text" name="parcial1" value="<?=$this->alumno['resultado1']?>"></td>
		    <td><input type="text" name="parcial2" value="<?=$this->alumno['resultado2']?>"></td>
		    <td><input type="Submit" value="guardar"></td>
		  </tr>
		</tbody>
		</table>
	</div>
</div>