<script>
	$(document).ready(function() {
		$('select').material_select();
	});
</script>
<div class="container">
	<div class="row">
		<div class="col s12 m12">
			<h2 class="col s12 header"><?=$this->alumno['cnombre']?></h2>
			<p class="promo-caption"><?=$this->alumno['anombre']?> <?=$this->alumno['apellido_paterno']?> <?=$this->alumno['apellido_materno']?></p>
		</div>
	</div>
	<div class="row">
		<div class="col s12 m12">
		<form method="post" action="/Maestro/calificar?claseid=<?=$this->alumno['pcid']?>&alumnoid=<?=$this->alumno['aid']?>">
			<table class="hoverable">
			<thead>
			  <tr>
			      <th >Parcial 1</th>
			      <th >Parcial 2</th>
			      <th >Participación</th>
			      <th >Puntualidad</th>
			      <th >Disposición</th>
			      <th >Tareas</th>
			      <th >Observaciones</th>
			      <th ></th>
			  </tr>
			</thead>
			<tbody>
			  <tr>
			    <td><input type="text" name="parcial1" value="<?=$this->alumno['parcial1']?>"></td>
			    <td><input type="text" name="parcial2" value="<?=$this->alumno['parcial2']?>"></td>

			    <td>
			    	<select name="participacion" value="<?=$this->alumno['participacion']?>">
			    		<option value="E">Excelente</option>
			    		<option value="MB">Muy Bien</option>
			    		<option value="B">Bien</option>
			    		<option value="R">Regular</option>
			    		<option value="EP">En Proceso</option>
			    		<option value="NL">No Logrado</option>
			    	</select>
			    </td>
			    <td>
			    	<select name="puntualidad" value="<?=$this->alumno['puntualidad']?>">
			    		<option value="E">Excelente</option>
			    		<option value="MB">Muy Bien</option>
			    		<option value="B">Bien</option>
			    		<option value="R">Regular</option>
			    		<option value="EP">En Proceso</option>
			    		<option value="NL">No Logrado</option>
			    	</select>
			    </td>
			    <td>
			    	<select name="disposicion" value="<?=$this->alumno['disposicion']?>">
			    		<option value="E">Excelente</option>
			    		<option value="MB">Muy Bien</option>
			    		<option value="B">Bien</option>
			    		<option value="R">Regular</option>
			    		<option value="EP">En Proceso</option>
			    		<option value="NL">No Logrado</option>
			    	</select>
			    </td>
			    <td>
			    	<select name="tareas" value="<?=$this->alumno['tareas']?>">
			    		<option value="E">Excelente</option>
			    		<option value="MB">Muy Bien</option>
			    		<option value="B">Bien</option>
			    		<option value="R">Regular</option>
			    		<option value="EP">En Proceso</option>
			    		<option value="NL">No Logrado</option>
			    	</select>
			    </td>

			    <td><textarea name="observaciones"><?=$this->alumno['observaciones']?></textarea></td>
			    <td><button class="btn waves-effect waves-light" type="Submit">guardar</button></td>
			  </tr>
			</tbody>
			</table>
		</div>
	</div>
</div>

