<div class="container">
	<div class="row">
		<div class="col s12 m6">
			<h2 class="col s12 header"><?=$this->clases[0]['cnombre']?></h2>
		</div>
	</div>
	<div class="row">
		<div class="col s12 m6">
			<table class="hoverable">
			<thead>
			  <tr>
			      <th >Nombre</th>
			      <th >Parcial 1</th>
			      <th >Parcial 2</th>
			      <th ></th>
			  </tr>
			</thead>

			<tbody>
			<?php foreach ($this->clases as $clase) : ?>
			  <tr>
			    <td><?=$clase['anombre']?> <?=$clase['apellido_paterno']?> <?=$clase['apellido_materno']?></td>
			    <td><?=$clase['resultado1']?></td>
			    <td><?=$clase['resultado2']?></td>
			    <td><a class="btn waves-effect waves-light" href="/Maestro/calificar?claseid=<?=$clase['pcid']?>&alumnoid=<?=$clase['aid']?>">Modificar-></a></td>
			  </tr>
			<?php endforeach; ?>
			</tbody>
			</table>
		</div>
	</div>
</div>