<div class="row">
	<div class="large-12 columns">
        <?php foreach ($alumnovar as $alumno) : ?>
        		<div class="large-4 medium-6 small-12 panel columns">
        			<div class="large-10 columns">
		                <?php echo $this->escapeHtml($alumno->nombre);?>
	                </div>
	                <div class="large-2 columns">
		                <a href="/info/alumno/edit/<?php echo $this->escapeHtml($alumno->id);?>">Editar</a>
	                </div>
                </div>
        <?php endforeach; ?>
        <a href="/info/alumno/add" class="button">Agregar</a>
    </div>
</div>
