<div class="row">
      <div class="col s12 offset-m3 m6">
      <?php echo $this->mensaje; ?>
            <form action="/Paciente/alta" method="post">
                <input name="nombre" type="text" placeholder="Nombre">
                <input name="apellido_p" type="text" placeholder="Apellido Paterno">
                <input name="apellido_m" type="text" placeholder="Apellido Materno">
                <input name="curp" type="text" placeholder="CURP">
                <button class="btn waves-effect waves-teal orange" type="submit">Alta</button>
            </form>
      </div>
</div>