<img src="<?php echo $this->getSecureImage('Bleach.jpg'); ?>">
<div class="row">
	<div class="col s12">
	<a class="btn" href="/Paciente/alta">Dar alta de paciente</a>
	<?php foreach ($this->pacientes as $paciente) : ?>
		<div class="row">
			<div class="col s12 m6">
				<div class="card blue-grey darken-1">
					<div class="card-content white-text">
						<span class="card-title"><?php echo $paciente['nombre'].' '.$paciente['apellido_p'].' '.$paciente['apellido_m']; ?></span>
						<p><?php echo $paciente['curp']; ?></p>
					</div>
					<div class="card-action">
						<a href="#">This is a link</a>
						<a href="#">This is a link</a>
					</div>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	</div>
</div>