<div class="row">
    <div class="large-12 columns">
    	<section class="register-confirm">
<h2>Registro exitoso</h2>
<p>¡Muchas gracias por tu pre-registro, tenemos tu información guardada y te mantendremos informado de las novedades de Nucleum!</p>
<p>Lo único que falta es que debes realizar el pago en el banco de su preferencia en cualquiera de las siguientes cuentas: </p>
<div class="row cuentaboxrow">
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Bancomer
		<br><img src="/img/bancomer.jpg" />
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Cuenta: CONVENIO CIE:688517
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Referencia: <br>
		002020605100813111216 <br>
		Concepto: <br>
		Alan0Fernando0Rodrig <br>
	</div>
</div>
<div class="row cuentaboxrow">
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Banorte
		<br><img src="/img/banorte.gif" />
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Cuenta: EMISORA: 31898
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Referencia: <br>
		002020605100813111216 <br>
	</div>
</div>
<div class="row cuentaboxrow">
	<div class="large-4 medium-4 small-12 columns cuentabox">
		HSBC
		<br><img src="/img/hsbc.jpg" />
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Cuenta: TRANSACCI&Oacute;N: 5503 CLAVE: 7630
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Referencia 1: <br>
		002020605100813111216 <br>
		Referencia 2: <br>
		Alan0Fernando0Rodrig <br>
	</div>
</div>
<div class="row cuentaboxrow">
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Santander
		<br><img src="/img/santander.jpg" />
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Cuenta: CONVENIO: 0996
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Referencia: <br>
		002020605100813111216 <br>
	</div>
</div>
<div class="row cuentaboxrow">
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Banamex
		<br><img src="/img/banamex.jpg" />
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		CUENTA: 870-5160
	</div>
	<div class="large-4 medium-4 small-12 columns cuentabox">
		Referencia: <br>
		002020605100813111216 <br>
	</div>
</div>
<p>Una vez realizado el pago, enviar la ficha de pago (con la información legible) al correo holanucleum@gmail.com y esperar a recibir un correo de confirmado.</p>
<p>Más adelante nos pondremos en contacto para informarle a partir de cuándo podrá realizar su horario.</p>
</section>
<img src="/img/preregistro.jpg" />
	</div>
</div>