<div class="row">
    <div class="large-12 columns">
<section class="Registro">
<h2>Registro</h2>
<?php if ($this->error): ?>
<p class="error">
 Hubo errores en la información ingresada, favor de verificarlos. 
</p>
<?php endif ?>



<?php
	//Vista de Forma
	$form = $this->form;
	$form->prepare();

	$form->setAttribute('action', $this->url(NULL, array('controller'=>'Register', 'action' => 'index')));
	$form->setAttribute('data-abide', '');
	echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="large-4 medium-7 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('nombre')); ?>
		    <?php echo $this->formElement($form->get('nombre')); ?>
		    <small class="error">Este campo es requerido.</small>
		</div>
	</div>
	<div class="large-4 medium-6 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('apellido_paterno')); ?>
		    <?php echo $this->formElement($form->get('apellido_paterno')); ?>
		    <small class="error">Este campo es requerido.</small>
		</div>
	</div>
	<div class="large-4 medium-6 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('apellido_materno')); ?>
		    <?php echo $this->formElement($form->get('apellido_materno')); ?>
		    <small class="error">Este campo es requerido.</small>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-4 medium-7 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('email')); ?>
		    <?php echo $this->formElement($form->get('email')); ?>
		    <small class="error">Se requiere de un email v&aacute;lido.</small>
		</div>
	</div>
	<div class="large-4 medium-6 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('tel_cel')); ?>
		    <?php echo $this->formElement($form->get('tel_cel')); ?>
		    <small class="error">Este campo es requerido.</small>
		</div>
	</div>
	<div class="large-4 medium-6 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('estado')); ?>
		    <?php echo $this->formElement($form->get('estado')); ?>
		    <small class="error">Es requerido</small>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-4 medium-7 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('ciudad')); ?>
		    <?php echo $this->formElement($form->get('ciudad')); ?>
		    <small class="error">Este campo es requerido.</small>
		</div>
	</div>
	<div class="large-4 medium-6 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('institucion')); ?>
		    <?php echo $this->formElement($form->get('institucion')); ?>
		    <small class="error">Este campo es requerido.</small>
		</div>
	</div>
	<div class="large-4 medium-6 small-12 columns">
		<div class="field">
		    <?php echo $this->formLabel($form->get('grado')); ?>
		    <?php echo $this->formElement($form->get('grado')); ?>
		    <small class="error">Es requerido</small>
		</div>
	</div>
</div>
<?php echo $this->formElement($form->get('submit')); ?>

<?php echo $this->form()->closeTag() ?>
	</div>
</div>

