<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<div style="clear:both;"></div>

<style>
</style>

<div class="row">
	<div class="large-12 columns">
        <?php foreach ($talleres as $taller) : ?>
        		<div class="large-4 medium-6 small-12 panel columns">
        			<div class="large-10 columns">
		                <?php echo $this->escapeHtml($taller->nombre);?>
	                </div>
	                <div class="large-2 columns">
		                <a href="/info/talleres/edit/<?php echo $this->escapeHtml($taller->id);?>">Editar</a>
	                </div>
                </div>
        <?php endforeach; ?>
    </div>
</div>